### ISSUE TITLE
Player class unused methods

### ISSUE THREAD

**Issue by KevinRickard** [gildir/CS321-2018F-002#11]
There are several groups of unused methods (and a corresponding instance variable) in the Player class that are never used and should likely be removed:
1. DataOutputStream related
2. setName()
3. Inventory related

#### 1. DataOutputStream related
The Player class has the following fields:
```
    private DataOutputStream outputWriter = null;
    public void setOutputWriter(DataOutputStream writer) {...}
    public DataOutputStream getOutputWriter() {...}
```
But they are never used, and there are no other references to a DataOutputStream anywhere in the project. These should either be explained or removed if they have no use.

#### 2. setName()
There is an unused setter for the Player's name:
```public void setName(String name) {...}```
Which could be a large issue if someone ever called it, because (as far as I know) the way the game currently handles associating an action with a player is doing a lookup on that player's name (as a String). So if a Player object's name is changed by that setter, the corresponding (IRL) player's client will now have a defunct playername, with no matching player on the server, and none of their commands will work as intended.

#### 3. Inventory related
There are also methods:
```
    public LinkedList<String> getCurrentInventory() {...}
    public void setCurrentInventory(LinkedList<String> currentInventory) {...}
```
which are never used and should probably be removed because the player class already provides an interface for the inventory via:

    public void addObjectToInventory(String object) {...}
    public String viewInventory() {...}

p.s.: Is this where we're supposed to report feature/bug requests?

**Comment by gildir** [comment]
Nope, this is not where you should do this. There is a pinned post on Piazza for that. That said, on open source projects, this would normally be where you report this :)
